In [5]:
using HTTP, JSON3

In [6]:
#SWAPI, start wars API

In [7]:
url = "https://swapi.dev/api/people/1/"
response = HTTP.get(url)
character = JSON3.read(response.body)

# Display some details
println("Name: ", character.name)
println("Height: ", character.height, " cm")
println("Mass: ", character.mass, " kg")
println("Hair color: ", character.hair_color)

Name: Luke Skywalker
Height: 172 cm
Mass: 77 kg
Hair color: blond

In [8]:
function fetch_all_people()
    people = []
    next_url = "https://swapi.dev/api/people/"
    
    while !isnothing(next_url)
        response = HTTP.get(next_url)
        data = JSON3.read(response.body)
        append!(people, data.results)
        next_url = data.next  # Get the URL for the next page of results
    end
    
    return people
end

# Fetch all people
all_people = fetch_all_people()

#number of characters per species
species_count = Dict()
for person in all_people
    species = isempty(person.species) ? "Unknown" : basename(person.species[1])
    species_count[species] = get(species_count, species, 0) + 1
end

#  the count of characters in each species
for (spec, count) in species_count
    println("$spec: $count")
end

: 50
Unknown: 32

In [ ]:
# PokeAPI

In [9]:
url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response = HTTP.get(url)
pikachu = JSON3.read(response.body)

# Display some details about Pikachu
println("Name: ", pikachu.name)
println("ID: ", pikachu.id)
println("Height: ", pikachu.height, " (decimetres)")
println("Weight: ", pikachu.weight, " (hectograms)")
println("Types:")
for t in pikachu.types
    println("  - ", t.type.name)
end

Name: pikachu
ID: 25
Height: 4 (decimetres)
Weight: 60 (hectograms)
Types:
  - electric

In [10]:
function fetch_pokemon_by_type(type_name)
    url = "https://pokeapi.co/api/v2/type/" * type_name
    response = HTTP.get(url)
    type_data = JSON3.read(response.body)

    println("Pokémon of type ", type_name, ":")
    for pokemon in type_data.pokemon
        println("  - ", pokemon.pokemon.name)
    end
end

# Fetch and list all fire-type Pokémon
fetch_pokemon_by_type("fire")

Pokémon of type fire:
  - charmander
  - charmeleon
  - charizard
  - vulpix
  - ninetales
  - growlithe
  - arcanine
  - ponyta
  - rapidash
  - magmar
  - flareon
  - moltres
  - cyndaquil
  - quilava
  - typhlosion
  - slugma
  - magcargo
  - houndour
  - houndoom
  - magby
  - entei
  - ho-oh
  - torchic
  - combusken
  - blaziken
  - numel
  - camerupt
  - torkoal
  - chimchar
  - monferno
  - infernape
  - magmortar
  - heatran
  - victini
  - tepig
  - pignite
  - emboar
  - pansear
  - simisear
  - darumaka
  - darmanitan-standard
  - litwick
  - lampent
  - chandelure
  - heatmor
  - larvesta
  - volcarona
  - reshiram
  - fennekin
  - braixen
  - delphox
  - fletchinder
  - talonflame
  - litleo
  - pyroar
  - volcanion
  - litten
  - torracat
  - incineroar
  - oricorio-baile
  - salandit
  - salazzle
  - turtonator
  - blacephalon
  - scorbunny
  - raboot
  - cinderace
  - carkol
  - coalossal
  - sizzlipede
  - centiskorch
  - fuecoco
  - crocalor
  - skeledirge
  - charcadet
  - armarouge
  - ceruledge
  - scovillain
  - iron-moth
  - chi-yu
  - gouging-fire
  - rotom-heat
  - castform-sunny
  - darmanitan-zen
  - charizard-mega-x
  - charizard-mega-y
  - houndoom-mega
  - blaziken-mega
  - groudon-primal
  - camerupt-mega
  - marowak-alola
  - salazzle-totem
  - marowak-totem
  - darmanitan-galar-zen
  - charizard-gmax
  - cinderace-gmax
  - coalossal-gmax
  - centiskorch-gmax
  - growlithe-hisui
  - arcanine-hisui
  - typhlosion-hisui
  - tauros-paldea-blaze-breed
  - ogerpon-hearthflame-mask

In [14]:
#world bank data

In [15]:
country_code = "US"  #country code for the United States
indicator_code = "NY.GDP.MKTP.CD"  #indicator code for GDP
url = "http://api.worldbank.org/v2/country/$(country_code)/indicator/$(indicator_code)?format=json"


response = HTTP.get(url)
data = JSON3.read(response.body)

#data is in the second element of the returned array
if length(data) > 1
    gdp_data = data[2]
    for entry in gdp_data
        if !isnothing(entry.value)
            println("Year: ", entry.date, " - GDP: \$", entry.value)
        end
    end
else
    println("No data available")
end

Year: 2022 - GDP: $25439700000000
Year: 2021 - GDP: $23315080560000
Year: 2020 - GDP: $21060473613000
Year: 2019 - GDP: $21380976119000
Year: 2018 - GDP: $20533057312000
Year: 2017 - GDP: $19477336549000
Year: 2016 - GDP: $18695110842000
Year: 2015 - GDP: $18206020741000
Year: 2014 - GDP: $17550680174000
Year: 2013 - GDP: $16843190993000
Year: 2012 - GDP: $16253972230000
Year: 2011 - GDP: $15599728123000
Year: 2010 - GDP: $15048964444000
Year: 2009 - GDP: $14478064934000
Year: 2008 - GDP: $14769857911000
Year: 2007 - GDP: $14474226905000
Year: 2006 - GDP: $13815586948000
Year: 2005 - GDP: $13039199193000
Year: 2004 - GDP: $12217193198000
Year: 2003 - GDP: $11456442041000
Year: 2002 - GDP: $10929112955000
Year: 2001 - GDP: $10581929774000
Year: 2000 - GDP: $10250947997000
Year: 1999 - GDP: $9631174489000
Year: 1998 - GDP: $9062818202000
Year: 1997 - GDP: $8577554457000
Year: 1996 - GDP: $8073122000000
Year: 1995 - GDP: $7639749000000
Year: 1994 - GDP: $7287236000000
Year: 1993 - GDP: $6858559000000
Year: 1992 - GDP: $6520327000000
Year: 1991 - GDP: $6158129000000
Year: 1990 - GDP: $5963144000000
Year: 1989 - GDP: $5641580000000
Year: 1988 - GDP: $5236438000000
Year: 1987 - GDP: $4855215000000
Year: 1986 - GDP: $4579631000000
Year: 1985 - GDP: $4338979000000
Year: 1984 - GDP: $4037613000000
Year: 1983 - GDP: $3634038000000
Year: 1982 - GDP: $3343789000000
Year: 1981 - GDP: $3207041000000
Year: 1980 - GDP: $2857307000000
Year: 1979 - GDP: $2627333000000
Year: 1978 - GDP: $2351599000000
Year: 1977 - GDP: $2081826000000
Year: 1976 - GDP: $1873412000000
Year: 1975 - GDP: $1684904000000
Year: 1974 - GDP: $1545243000000

In [16]:

#  the URL for fetching life expectancy data for Japan
country_code = "JP"  #country code for Japan
indicator_code = "SP.DYN.LE00.IN"  # idicator code for life expectancy at birth
url = "http://api.worldbank.org/v2/country/$(country_code)/indicator/$(indicator_code)?format=json&per_page=60"  # Increase per_page if you need more entries


response = HTTP.get(url)
data = JSON3.read(response.body)


if length(data) > 1 && !isempty(data[2])
    life_expectancy_data = data[2]
    println("Life Expectancy at Birth in Japan (Years):")
    for entry in life_expectancy_data
        year = entry.date
        value = entry.value
        if !isnothing(value)
            println("Year: $year - Life Expectancy: $value")
        end
    end
else
    println("No data available.")
end

Life Expectancy at Birth in Japan (Years):
Year: 2021 - Life Expectancy: 84.4456097560976
Year: 2020 - Life Expectancy: 84.56
Year: 2019 - Life Expectancy: 84.3563414634146
Year: 2018 - Life Expectancy: 84.2109756097561
Year: 2017 - Life Expectancy: 84.099756097561
Year: 2016 - Life Expectancy: 83.9848780487805
Year: 2015 - Life Expectancy: 83.7939024390244
Year: 2014 - Life Expectancy: 83.5878048780488
Year: 2013 - Life Expectancy: 83.3319512195122
Year: 2012 - Life Expectancy: 83.0960975609756
Year: 2011 - Life Expectancy: 82.5912195121951
Year: 2010 - Life Expectancy: 82.8426829268293
Year: 2009 - Life Expectancy: 82.9314634146342
Year: 2008 - Life Expectancy: 82.5875609756098
Year: 2007 - Life Expectancy: 82.5070731707317
Year: 2006 - Life Expectancy: 82.3219512195122
Year: 2005 - Life Expectancy: 81.9551219512195
Year: 2004 - Life Expectancy: 82.030243902439
Year: 2003 - Life Expectancy: 81.76
Year: 2002 - Life Expectancy: 81.6907317073171
Year: 2001 - Life Expectancy: 81.4163414634146
Year: 2000 - Life Expectancy: 81.0760975609756
Year: 1999 - Life Expectancy: 80.4609756097561
Year: 1998 - Life Expectancy: 80.5014634146342
Year: 1997 - Life Expectancy: 80.4241463414634
Year: 1996 - Life Expectancy: 80.219756097561
Year: 1995 - Life Expectancy: 79.5360975609756
Year: 1994 - Life Expectancy: 79.6968292682927
Year: 1993 - Life Expectancy: 79.3036585365854
Year: 1992 - Life Expectancy: 79.080243902439
Year: 1991 - Life Expectancy: 79.0368292682927
Year: 1990 - Life Expectancy: 78.8370731707317
Year: 1989 - Life Expectancy: 78.7685365853659
Year: 1988 - Life Expectancy: 78.349756097561
Year: 1987 - Life Expectancy: 78.429512195122
Year: 1986 - Life Expectancy: 78.0104878048781
Year: 1985 - Life Expectancy: 77.5604878048781
Year: 1984 - Life Expectancy: 77.2912195121951
Year: 1983 - Life Expectancy: 76.9219512195122
Year: 1982 - Life Expectancy: 76.8736585365854
Year: 1981 - Life Expectancy: 76.3948780487805
Year: 1980 - Life Expectancy: 75.9890243902439
Year: 1979 - Life Expectancy: 76.1087804878049
Year: 1978 - Life Expectancy: 75.5846341463415
Year: 1977 - Life Expectancy: 75.2558536585366
Year: 1976 - Life Expectancy: 74.6865853658537
Year: 1975 - Life Expectancy: 74.2470731707317
Year: 1974 - Life Expectancy: 73.6721951219512
Year: 1973 - Life Expectancy: 73.2951219512195
Year: 1972 - Life Expectancy: 73.1536585365854
Year: 1971 - Life Expectancy: 72.8090243902439
Year: 1970 - Life Expectancy: 71.919756097561
Year: 1969 - Life Expectancy: 71.8580487804878
Year: 1968 - Life Expectancy: 71.6109756097561
Year: 1967 - Life Expectancy: 71.4660975609756
Year: 1966 - Life Expectancy: 70.9158536585366
Year: 1965 - Life Expectancy: 70.2668292682927
Year: 1964 - Life Expectancy: 70.2065853658537